import { useState, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import {
  karaokeService,
  KaraokeTrack,
  LyricLine,
} from "@/api/services/karaokeService";
import { songService } from "@/api/services/songService";
import { AudioPlayer } from "@/components/practice/AudioPlayer";
import { LyricsEditor } from "@/components/karaoke/LyricsEditor";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Spinner } from "@/components/ui/Spinner";
import { motion, AnimatePresence } from "framer-motion";
import { Edit3, Music, ListMusic } from "lucide-react";

interface KaraokePlayerProps {
  songId: number;
}

export const KaraokePlayer: React.FC<KaraokePlayerProps> = ({ songId }) => {
  const [isLyricsEditorOpen, setIsLyricsEditorOpen] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [songDuration, setSongDuration] = useState(300);

  const { data: karaokeTrack, isLoading } = useQuery({
    queryKey: ["karaoke-track", songId],
    queryFn: () => karaokeService.getTrack(songId),
  });

  // Fetch song parts (auto-generated by AI)
  const { data: songParts } = useQuery({
    queryKey: ["song-parts", songId],
    queryFn: () => songService.getSongParts(songId),
  });

  // Derived value - no useEffect needed!
  const currentLyricIndex = useMemo(() => {
    if (!karaokeTrack?.lyrics_data || karaokeTrack.lyrics_data.length === 0) {
      return -1;
    }
    return karaokeTrack.lyrics_data.findIndex(
      (lyric) => currentTime >= lyric.start && currentTime <= lyric.end,
    );
  }, [currentTime, karaokeTrack]);

  if (isLoading) return <Spinner />;
  if (!karaokeTrack) return null;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <Badge variant="sage">Ready</Badge>
        <Button
          variant="outline"
          size="sm"
          onClick={() => setIsLyricsEditorOpen(true)}
        >
          <Edit3 className="w-4 h-4 mr-1" />
          Edit Lyrics
        </Button>
      </div>

      {/* Instrumental Player - Pass raw path, let AudioPlayer handle URL resolution */}
      {karaokeTrack.instrumental_file_path && (
        <AudioPlayer
          src={karaokeTrack.instrumental_file_path}
          title="Instrumental"
          onTimeUpdate={setCurrentTime}
        />
      )}

      {/* Lyrics Display - TV Style */}
      {karaokeTrack.lyrics_data && karaokeTrack.lyrics_data.length > 0 && (
        <div className="relative bg-loft-plum-900 rounded-xl p-6 min-h-[200px] overflow-hidden">
          {/* Decorative background */}
          <div className="absolute inset-0 bg-gradient-to-b from-loft-plum-800 to-loft-plum-900 opacity-50" />

          <div className="relative z-10 flex items-center justify-center h-full">
            <AnimatePresence mode="wait">
              <motion.div
                key={currentLyricIndex}
                initial={{ opacity: 0, y: 20, scale: 0.9 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                exit={{ opacity: 0, y: -20, scale: 0.9 }}
                transition={{
                  type: "spring",
                  damping: 20,
                  stiffness: 200,
                  duration: 0.5,
                }}
                className="text-center"
              >
                {currentLyricIndex >= 0 ? (
                  <>
                    {/* Current lyric */}
                    <p className="text-3xl font-display text-brass-gold-400 font-bold">
                      {karaokeTrack.lyrics_data[currentLyricIndex]?.text}
                    </p>

                    {/* Next lyric preview */}
                    {currentLyricIndex + 1 <
                      karaokeTrack.lyrics_data.length && (
                      <p className="text-lg text-loft-plum-400 mt-3 opacity-70">
                        {karaokeTrack.lyrics_data[currentLyricIndex + 1]?.text}
                      </p>
                    )}
                  </>
                ) : (
                  <p className="text-xl text-loft-plum-400">
                    <Music className="w-8 h-8 mx-auto mb-2" />
                    Waiting for lyrics...
                  </p>
                )}
              </motion.div>
            </AnimatePresence>
          </div>
        </div>
      )}

      {/* Generated Voice Parts */}
      {songParts && songParts.length > 0 && (
        <div>
          <h4 className="font-medium text-loft-plum-900 mb-2 flex items-center">
            <ListMusic className="w-4 h-4 mr-2" />
            AI-Generated Voice Parts
          </h4>
          <div className="grid grid-cols-2 gap-3">
            {songParts.map((part) => (
              <div key={part.id} className="bg-loft-plum-50 rounded-lg p-3">
                <p className="text-sm font-medium text-loft-plum-900 capitalize mb-2">
                  {part.partType}
                </p>
                {part.audioFilePath && (
                  // Pass raw path, let AudioPlayer handle URL resolution
                  <AudioPlayer src={part.audioFilePath} />
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Lyrics Editor Modal */}
      <LyricsEditor
        songId={songId}
        isOpen={isLyricsEditorOpen}
        onClose={() => setIsLyricsEditorOpen(false)}
        currentLyrics={karaokeTrack.lyrics_data}
        songDuration={songDuration}
      />
    </div>
  );
};
